### ISSUE TITLE
Can't find variable setTimeout

### ISSUE THREAD

**Issue by Qlenglet** [orYoffe/create-react-native-web-app#47]
Hello everyone
I have the issue in the title when I am trying to use the basic set-up of the tool.

This issue only appear when I'm trying to launch the application for Android and I can't see how I can fix this.

I have the last version of all the react element and I use yarn to install the component.

Thank you for your help

**Comment by bigorangemachine** [comment]
I also have this issue.

Did you have any luck figuring it out?

**Comment by bigorangemachine** [comment]
This issue should be closed.

Probably developer error not an issue with the current framework

**Comment by sunildate05** [comment]
> I also have this issue.
> Did you have any luck figuring it out?
> [Edit]
> I updated the react-native version without updating the android/ and ios/ directory

Hi @bigorangemachine ,
I'm also facing same issue. I have upgraded react native 0.55 to 0.59.10 for 64bit APK build.
Please let me know which version you have updated.

Thanks.

**Comment by bigorangemachine** [comment]
The issue is following the googles all the way down.  Honestly just better to go from `react-native init`.  The problem is that the `metro` babel preset conflicts with babel react-app.  You have to used fixed version of those libraries but honestly its just a pain... start from `react-native init` steps as per the official website.
