### ISSUE TITLE
React native vector icons is giving error as 'classProperties' isn't currently enabled

### ISSUE THREAD

**Issue by Yajan** [orYoffe/create-react-native-web-app#64]
When I add react-native-vector-icons to the project I get an error as Add @babel/plugin-proposal-class-properties (https://git.io/vb4SL) to the 'plugins' section of your Babel config to enable transformation. Can you please update the project to handle class properties.

**Comment by orYoffe** [comment]
when you add some es6 libraries that need to be compiled since they don'\t have an es5 version already inside like most react native packages you need to tell webpack to add them.

you can add in each of your webpack configs the library like this
```
// Process application JS with Babel.
          // The preset includes JSX, Flow, and some ESnext features.
          {
            test: /\.(js|mjs|jsx|ts|tsx)$/,
            include: [
              paths.appSrc,
              `${paths.appNodeModules}/react-native-vector-icons`
            ],
            loader: require.resolve('babel-loader'),
```

here: https://github.com/orYoffe/create-react-native-web-app/blob/master/template/config/webpack.config.dev.js#L216
and here: https://github.com/orYoffe/create-react-native-web-app/blob/master/template/config/webpack.config.prod.js#L289

**Comment by orenhaliva** [comment]
after doing it the compiler still doesn't like my package
![image](https://user-images.githubusercontent.com/18486806/73752324-6e8b9100-4769-11ea-801b-49d5a54326aa.png)

**Comment by MahmoudShaeer** [comment]
+1

**Comment by orYoffe** [comment]
@orenhaliva the compiler complains about JSX in the screenshot.. meaning that that node_modules/<folder> was not compiled by babel properly, so you would need to add it in both places in the webpack config.. If you'd like further help I would need more details and examples
