### ISSUE TITLE
What is the Navigation Recomendation for this Project?

### ISSUE THREAD

**Issue by galuh1300d** [orYoffe/create-react-native-web-app#77]

**Comment by orYoffe** [comment]
Hi @galuh1300d 

I would say if you're starting out react-router would be the easiest to implement. Mainly since they have almost the same api for both native and web https://reacttraining.com/react-router/native/guides/quick-start

There are other more advanced and complex solutions that try to give more native feel to navigation with stack navigation like react-navigation and react native navigation. Though i haven't tried these two myself, I hear many recommendations from react native developers for them.
